import { useEffect, useState, type ReactNode } from 'react'
import { useAuth } from '../auth/AuthProvider'
import { navigate } from '../app/router'
import { Icon, type IconName, SearchInput } from './ui'
import { apiRequest } from '../api/client'

type PageKey = 'overview' | 'not-found' | 'documents' | 'intelligence' | 'analytics' | 'gis' | 'query' | 'reports' | 'verification' | 'audit' | 'settings'
const navigation: { key: PageKey; label: string; icon: IconName; path: string; roles?: string[] }[] = [
  {key:'overview',label:'Overview',icon:'overview',path:'/'},{key:'documents',label:'Documents',icon:'documents',path:'/documents'},{key:'intelligence',label:'Intelligence',icon:'intelligence',path:'/intelligence'},{key:'analytics',label:'Analytics',icon:'analytics',path:'/analytics'},{key:'gis',label:'GIS',icon:'gis',path:'/gis'},{key:'query',label:'Query Console',icon:'query',path:'/query'},{key:'reports',label:'Reports',icon:'reports',path:'/reports'},{key:'verification',label:'Verification',icon:'verification',path:'/verification',roles:['ADMIN','VERIFIER']},{key:'audit',label:'Audit',icon:'audit',path:'/audit'},{key:'settings',label:'Settings',icon:'settings',path:'/settings'}]
export function AppShell({ page, children }: {page: PageKey; children: ReactNode}) {
  const {user, signOut} = useAuth(); const [collapsed,setCollapsed]=useState(false); const [mobileOpen,setMobileOpen]=useState(false); const [search,setSearch]=useState(''); const [accountOpen,setAccountOpen]=useState(false)
  const [apiStatus,setApiStatus]=useState<'checking'|'online'|'offline'>('checking')
  useEffect(()=>{setMobileOpen(false)},[page])
  useEffect(()=>{const controller=new AbortController();apiRequest('/health',{},controller.signal).then(()=>setApiStatus('online')).catch(()=>setApiStatus('offline'));return()=>controller.abort()},[])
  const role = user?.role.toUpperCase() ?? ''
  const viewerNavigation: PageKey[] = ['overview', 'query', 'analytics', 'gis', 'intelligence', 'reports', 'audit']
  const items = role === 'VIEWER'
    ? viewerNavigation.map(key => navigation.find(item => item.key === key)).filter((item): item is typeof navigation[number] => item !== undefined)
    : navigation.filter(item => !item.roles || item.roles.includes(role))
  function globalSearch(){const value=search.trim();if(value){navigate(`/query?q=${encodeURIComponent(value)}`);setSearch('')}}
  const apiStatusLabel=apiStatus==='checking'?'Checking API':apiStatus==='online'?'API available':'API unavailable'
  return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}>
    {mobileOpen&&<button className="mobile-scrim" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>}
    <aside className={`sidebar ${mobileOpen?'mobile-open':''}`}><div className="sidebar-brand"><div className="brand-mark"><span/><span/><span/></div><div className="brand-wordmark"><strong>DATA MINE</strong><small>INTELLIGENCE PLATFORM</small></div><button className="icon-button sidebar-close" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}><Icon name="close"/></button></div><div className="sidebar-section-label">WORKSPACE</div><nav aria-label="Main navigation">{items.map(item=><button key={item.key} className={`nav-item ${page===item.key?'active':''}`} onClick={()=>{setMobileOpen(false);navigate(item.path)}} aria-current={page===item.key?'page':undefined}><Icon name={item.icon}/><span>{item.label}</span>{page===item.key&&<i className="active-indicator"/>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-divider"/><div className="sidebar-footnote"><span className={`status-dot ${apiStatus==='online'?'online':apiStatus==='offline'?'offline':'checking'}`}/><span>{apiStatusLabel}</span></div><button className="collapse-control" onClick={()=>setCollapsed(v=>!v)}><Icon name="chevron"/><span>{collapsed?'Expand':'Collapse sidebar'}</span></button></div></aside>
    <div className="main-frame"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobileOpen(true)}><Icon name="menu"/></button><div className="breadcrumb"><span>Workspace</span><Icon name="chevron" size={14}/><strong>{page==='overview'?'Overview':page==='not-found'?'Page not found':navigation.find(item=>item.key===page)?.label}</strong></div></div><div className="topbar-search"><SearchInput value={search} onChange={setSearch} onSubmit={globalSearch} placeholder="Search documents and evidence…"/></div><div className="topbar-actions"><div className="header-health"><span className={`status-dot ${apiStatus==='online'?'online':apiStatus==='offline'?'offline':'checking'}`}/><span>{apiStatusLabel}</span></div><button className="icon-button notification-button" aria-label="Notifications are not available"><Icon name="bell"/></button><div className="account-wrap"><button className="account-button" aria-expanded={accountOpen} onClick={()=>setAccountOpen(v=>!v)}><span className="avatar">{user?.username.slice(0,1).toUpperCase()??'U'}</span><span className="account-label"><strong>{user?.username}</strong><small>{user?.role}</small></span><Icon name="chevron" size={14}/></button>{accountOpen&&<div className="account-menu"><div className="account-menu-info"><strong>{user?.username}</strong><span>{user?.role}</span></div><button onClick={()=>{signOut();navigate('/login')}}><Icon name="logout" size={16}/> Sign out</button></div>}</div></div></header><main className="workspace-content">{children}<footer className="app-footer"><span>DATA MINE · Evidence-led geological and mining intelligence</span><span>Frontend foundation</span></footer></main></div>
  </div>
}
