import { useEffect, useState, type ReactNode } from 'react'

export type IconName = 'overview' | 'documents' | 'intelligence' | 'analytics' | 'gis' | 'query' | 'reports' | 'verification' | 'audit' | 'settings' | 'search' | 'bell' | 'menu' | 'close' | 'chevron' | 'logout' | 'external' | 'filter' | 'layers' | 'activity' | 'shield' | 'arrow'
const paths: Record<IconName, ReactNode> = {
  overview: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
  documents: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h8"/></>,
  intelligence: <><path d="M12 3a7 7 0 0 0-4 12.74V19h8v-3.26A7 7 0 0 0 12 3Z"/><path d="M9 22h6M12 7v3m-3 1 2 2m5-2-2 2"/></>,
  analytics: <><path d="M3 3v18h18"/><path d="m7 14 4-4 4 3 6-7"/></>, gis: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
  query: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4M8 11h6M11 8v6"/></>, reports: <><path d="M4 4h16v16H4zM8 8h8M8 12h8M8 16h5"/></>,
  verification: <><path d="M12 22s8-4 8-11V5l-8-3-8 3v6c0 7 8 11 8 11Z"/><path d="m9 12 2 2 4-4"/></>, audit: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
  settings: <><circle cx="12" cy="12" r="3"/><path d="m19.4 15 .1.1 1.4 1.1-1.4 2.4-1.7-.6a8 8 0 0 1-1.6.9l-.3 1.8h-2.8l-.3-1.8a8 8 0 0 1-1.6-.9l-1.7.6-1.4-2.4L7.5 15a8 8 0 0 1 0-1.9L6.1 12l1.4-2.4 1.7.6a8 8 0 0 1 1.6-.9l.3-1.8h2.8l.3 1.8a8 8 0 0 1 1.6.9l1.7-.6 1.4 2.4-1.4 1.1a8 8 0 0 1-.1 1.9Z"/></>,
  search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,
  menu: <><path d="M4 6h16M4 12h16M4 18h16"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, chevron: <path d="m9 18 6-6-6-6"/>, logout: <><path d="M10 17l5-5-5-5M15 12H3"/><path d="M12 3h6a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-6"/></>, external: <><path d="M14 3h7v7M10 14 21 3"/><path d="M19 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h6"/></>, filter: <><path d="M4 7h16M7 12h10m-7 5h4"/><circle cx="8" cy="7" r="1"/><circle cx="15" cy="12" r="1"/></>, layers: <><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/></>, activity: <><path d="M3 12h4l3-8 4 16 3-8h4"/></>, shield: <><path d="M12 22s8-4 8-11V5l-8-3-8 3v6c0 7 8 11 8 11Z"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>
}
export function Icon({ name, size = 18 }: { name: IconName; size?: number }) { return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg> }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">DATA MINE / WORKSPACE</div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }
export function Card({ children, title, detail, className = '' }: { children: ReactNode; title?: string; detail?: string; className?: string }) { return <section className={`card ${className}`}>{(title || detail) && <header className="card-heading"><div>{title && <h2>{title}</h2>}{detail && <p>{detail}</p>}</div></header>}{children}</section> }
export function StatusBadge({ status }: { status: string }) { const tone = /ok|ready|complete|verified|success|active|available/i.test(status) ? 'good' : /insufficient|pending|processing|queued/i.test(status) ? 'caution' : /failed|error|unavailable/i.test(status) ? 'bad' : 'neutral'; return <span className={`badge badge-${tone}`}><i />{status.replace(/_/g, ' ')}</span> }
export function DataState({ kind, title, detail, onRetry }: { kind: 'loading' | 'empty' | 'error' | 'insufficient' | 'unauthorized' | 'forbidden'; title?: string; detail?: string; onRetry?: () => void }) { return <div className={`data-state state-${kind}`} role={kind === 'error' || kind === 'unauthorized' || kind === 'forbidden' ? 'alert' : 'status'}>{kind === 'loading' && <span className="spinner" aria-hidden="true"/>}<strong>{title ?? ({ loading: 'Loading live data…', empty: 'No records available', error: 'Could not load data', insufficient: 'INSUFFICIENT VERIFIED DATA', unauthorized: 'Sign in required', forbidden: 'Access denied' }[kind])}</strong>{detail && <p>{detail}</p>}{onRetry && <button className="button button-secondary button-small" onClick={onRetry}>Try again</button>}</div> }
export function SearchInput({ value, onChange, onSubmit, placeholder = 'Search' }: { value: string; onChange(value: string): void; onSubmit?(): void; placeholder?: string }) { return <label className="search-input"><Icon name="search"/><input aria-label={placeholder} value={value} onChange={e => onChange(e.target.value)} onKeyDown={e => e.key === 'Enter' && onSubmit?.()} placeholder={placeholder}/></label> }
export function FilterBar({ children }: { children: ReactNode }) { return <div className="filter-bar"><Icon name="filter"/>{children}</div> }
export function Tabs({ tabs, selected, onChange }: { tabs: string[]; selected: string; onChange(tab: string): void }) { return <div className="tabs" role="tablist">{tabs.map(tab => <button key={tab} role="tab" aria-selected={tab === selected} className={selected === tab ? 'selected' : ''} onClick={() => onChange(tab)}>{tab}</button>)}</div> }
export function Pagination({ page, onChange, hasNext = false }: { page: number; onChange(page: number): void; hasNext?: boolean }) { return <div className="pagination"><span>Page {page}</span><div><button className="button button-secondary button-small" disabled={page <= 1} onClick={() => onChange(page - 1)}>Previous</button><button className="button button-secondary button-small" disabled={!hasNext} onClick={() => onChange(page + 1)}>Next</button></div></div> }
export function DataTable({ columns, rows, rowKey }: { columns: { key: string; label: string; render?(row: Record<string, unknown>): ReactNode }[]; rows: Record<string, unknown>[]; rowKey: string }) { return <div className="table-wrap"><table><thead><tr>{columns.map(c => <th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={String(row[rowKey] ?? i)}>{columns.map(c => <td key={c.key}>{c.render ? c.render(row) : String(row[c.key] ?? '—')}</td>)}</tr>)}</tbody></table></div> }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose(): void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><Icon name="close"/></button></header>{children}</section></div> }
export function Drawer({ title, children, onClose }: { title: string; children: ReactNode; onClose(): void }) { return <div className="drawer-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><aside className="drawer" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" aria-label="Close" onClick={onClose}><Icon name="close"/></button></header>{children}</aside></div> }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="tooltip" tabIndex={0} aria-label={label} data-tooltip={label}>{children}</span> }
export function ConfirmDialog({ open, title, children, onConfirm, onCancel }: { open: boolean; title: string; children: ReactNode; onConfirm(): void; onCancel(): void }) { if (!open) return null; return <Modal title={title} onClose={onCancel}><div className="modal-content">{children}<div className="modal-actions"><button className="button button-secondary" onClick={onCancel}>Cancel</button><button className="button button-primary" onClick={onConfirm}>Confirm</button></div></div></Modal> }
export function Toast({ message, onDismiss }: { message: string; onDismiss(): void }) { return <div className="toast" role="status">{message}<button onClick={onDismiss} aria-label="Dismiss">×</button></div> }
export function useDebouncedValue<T>(value: T, delay = 250) { const [debounced, setDebounced] = useState(value); useEffect(() => { const id = window.setTimeout(() => setDebounced(value), delay); return () => window.clearTimeout(id) }, [value, delay]); return debounced }
