"""initial application schema

Revision ID: 15deaa701c02
Revises: 
Create Date: 2026-09-24 18:43:44.820066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2.types
import pgvector.sqlalchemy.vector
from sqlalchemy.dialects import postgresql


revision: str = '15deaa701c02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('mine_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mines')),
    sa.UniqueConstraint('code', name=op.f('uq_mines_code'))
    )
    op.create_index('ix_mines_location', 'mines', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_mines_name'), 'mines', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('validation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('validation_rule', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','WARNING','ERROR','CRITICAL')", name=op.f('ck_validation_results_severity_valid')),
    sa.CheckConstraint("status IN ('PASSED','FAILED','WARNING')", name=op.f('ck_validation_results_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    op.create_index(op.f('ix_validation_results_created_at'), 'validation_results', ['created_at'], unique=False)
    op.create_index('ix_validation_results_entity', 'validation_results', ['entity_type', 'entity_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_documents_file_size_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_sha256_checksum'), 'documents', ['sha256_checksum'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('mining_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('project_code IS NULL OR length(project_code) > 0', name=op.f('ck_mining_projects_project_code_nonempty')),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_mining_projects_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mining_projects'))
    )
    op.create_index('ix_mining_projects_mine_name', 'mining_projects', ['mine_id', 'name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('boreholes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('borehole_identifier', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('elevation', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_depth', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('borehole_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_depth IS NULL OR total_depth >= 0', name=op.f('ck_boreholes_total_depth_nonnegative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_boreholes_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['mining_projects.id'], name=op.f('fk_boreholes_project_id_mining_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boreholes'))
    )
    op.create_index(op.f('ix_boreholes_document_id'), 'boreholes', ['document_id'], unique=False)
    op.create_index('ix_boreholes_location', 'boreholes', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_boreholes_project_id'), 'boreholes', ['project_id'], unique=False)
    op.create_index('ix_boreholes_project_identifier', 'boreholes', ['project_id', 'borehole_identifier'], unique=True)
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_document_versions_file_size_nonnegative')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_document_versions_version_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name=op.f('uq_document_versions_document_id')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_document_versions_storage_key'))
    )
    op.create_index(op.f('ix_document_versions_created_by'), 'document_versions', ['created_by'], unique=False)
    op.create_index('ix_document_versions_document_created', 'document_versions', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_versions_sha256_checksum'), 'document_versions', ['sha256_checksum'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_number > 0', name=op.f('ck_document_pages_page_number_positive')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_pages_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_version_id', 'page_number', name=op.f('uq_document_pages_document_version_id'))
    )
    op.create_index('ix_document_pages_version_page', 'document_pages', ['document_version_id', 'page_number'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('processor', sa.String(length=150), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED','PROCESSING','PARSING','OCR','TABLE_EXTRACTION','NORMALIZATION','VALIDATION','VERIFICATION_PENDING','COMPLETED','FAILED')", name=op.f('ck_processing_jobs_status_valid')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_processing_jobs_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_version_status', 'processing_jobs', ['document_version_id', 'status'], unique=False)
    op.create_table('borehole_intervals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('borehole_id', sa.Uuid(), nullable=False),
    sa.Column('top_depth', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('bottom_depth', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('lithology', sa.String(length=150), nullable=True),
    sa.Column('seam_material', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('interval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)', name=op.f('ck_borehole_intervals_confidence_range')),
    sa.CheckConstraint('top_depth >= 0 AND bottom_depth >= top_depth', name=op.f('ck_borehole_intervals_depth_range_valid')),
    sa.ForeignKeyConstraint(['borehole_id'], ['boreholes.id'], name=op.f('fk_borehole_intervals_borehole_id_boreholes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_borehole_intervals_source_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_borehole_intervals_source_page_id_document_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borehole_intervals'))
    )
    op.create_index('ix_borehole_intervals_borehole_depth', 'borehole_intervals', ['borehole_id', 'top_depth', 'bottom_depth'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_source_document_id'), 'borehole_intervals', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_source_page_id'), 'borehole_intervals', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_borehole_intervals_verification_status'), 'borehole_intervals', ['verification_status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('character_count IS NULL OR character_count >= 0', name=op.f('ck_document_chunks_character_count_nonnegative')),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_chunk_index_nonnegative')),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name=op.f('ck_document_chunks_token_count_nonnegative')),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], name=op.f('fk_document_chunks_document_page_id_document_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_chunks_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name=op.f('uq_document_chunks_document_version_id'))
    )
    op.create_index(op.f('ix_document_chunks_document_page_id'), 'document_chunks', ['document_page_id'], unique=False)
    op.create_index('ix_document_chunks_version_page', 'document_chunks', ['document_version_id', 'document_page_id'], unique=False)
    op.create_table('extracted_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_extracted_content_confidence_range')),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], name=op.f('fk_extracted_content_document_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_content'))
    )
    op.create_index('ix_extracted_content_page_type', 'extracted_content', ['document_page_id', 'content_type'], unique=False)
    op.create_table('extracted_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=False),
    sa.Column('table_order', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('table_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_extracted_tables_confidence_range')),
    sa.CheckConstraint('table_order > 0', name=op.f('ck_extracted_tables_table_order_positive')),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], name=op.f('fk_extracted_tables_document_page_id_document_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_tables')),
    sa.UniqueConstraint('document_page_id', 'table_order', name=op.f('uq_extracted_tables_document_page_id'))
    )
    op.create_index('ix_extracted_tables_document_page', 'extracted_tables', ['document_page_id'], unique=False)
    op.create_table('geological_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('borehole_id', sa.Uuid(), nullable=True),
    sa.Column('measurement_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('depth', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('measurement_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value IS NULL OR value::text NOT IN ('NaN','Infinity','-Infinity')", name=op.f('ck_geological_measurements_value_finite')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_geological_measurements_confidence_range')),
    sa.CheckConstraint('depth IS NULL OR depth >= 0', name=op.f('ck_geological_measurements_depth_nonnegative')),
    sa.ForeignKeyConstraint(['borehole_id'], ['boreholes.id'], name=op.f('fk_geological_measurements_borehole_id_boreholes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_geological_measurements_source_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_geological_measurements_source_page_id_document_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geological_measurements'))
    )
    op.create_index(op.f('ix_geological_measurements_borehole_id'), 'geological_measurements', ['borehole_id'], unique=False)
    op.create_index('ix_geological_measurements_borehole_type', 'geological_measurements', ['borehole_id', 'measurement_type'], unique=False)
    op.create_index(op.f('ix_geological_measurements_source_document_id'), 'geological_measurements', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_geological_measurements_source_page_id'), 'geological_measurements', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_geological_measurements_verification_status'), 'geological_measurements', ['verification_status'], unique=False)
    op.create_table('processing_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('QUEUED','PROCESSING','PARSING','OCR','TABLE_EXTRACTION','NORMALIZATION','VALIDATION','VERIFICATION_PENDING','COMPLETED','FAILED')", name=op.f('ck_processing_stages_stage_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_processing_stages_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_stages'))
    )
    op.create_index('ix_processing_stages_job_created', 'processing_stages', ['job_id', 'created_at'], unique=False)
    op.create_table('production_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mine_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('production_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('production_unit', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('achievement_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('achievement_unit', sa.String(length=50), nullable=True),
    sa.Column('achievement_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('overburden_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('overburden_unit', sa.String(length=50), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('record_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)', name=op.f('ck_production_records_confidence_range')),
    sa.CheckConstraint('mine_id IS NOT NULL OR project_id IS NOT NULL', name=op.f('ck_production_records_mine_or_project_required')),
    sa.CheckConstraint('period_end IS NULL OR period_end >= reporting_period', name=op.f('ck_production_records_reporting_period_valid')),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_production_records_mine_id_mines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['mining_projects.id'], name=op.f('fk_production_records_project_id_mining_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_production_records_source_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_production_records_source_page_id_document_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_records'))
    )
    op.create_index('ix_production_records_mine_period', 'production_records', ['mine_id', 'reporting_period'], unique=False)
    op.create_index('ix_production_records_project_period', 'production_records', ['project_id', 'reporting_period'], unique=False)
    op.create_index(op.f('ix_production_records_source_document_id'), 'production_records', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_production_records_source_page_id'), 'production_records', ['source_page_id'], unique=False)
    op.create_index(op.f('ix_production_records_verification_status'), 'production_records', ['verification_status'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('ACCEPT','EDIT','REJECT')", name=op.f('ck_verification_records_action_valid')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_verification_records_reviewer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_verification_records_source_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_verification_records_source_page_id_document_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_records'))
    )
    op.create_index('ix_verification_records_entity', 'verification_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_verification_records_reviewer_id'), 'verification_records', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_verification_records_source_document_id'), 'verification_records', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_verification_records_source_page_id'), 'verification_records', ['source_page_id'], unique=False)
    op.create_table('extracted_table_cells',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cell_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_extracted_table_cells_confidence_range')),
    sa.CheckConstraint('row_index >= 0 AND column_index >= 0', name=op.f('ck_extracted_table_cells_cell_indexes_nonnegative')),
    sa.ForeignKeyConstraint(['table_id'], ['extracted_tables.id'], name=op.f('fk_extracted_table_cells_table_id_extracted_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_table_cells')),
    sa.UniqueConstraint('table_id', 'row_index', 'column_index', name=op.f('uq_extracted_table_cells_table_id'))
    )
    op.create_index('ix_extracted_table_cells_table', 'extracted_table_cells', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extracted_table_cells_table', table_name='extracted_table_cells')
    op.drop_table('extracted_table_cells')
    op.drop_index(op.f('ix_verification_records_source_page_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_source_document_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_reviewer_id'), table_name='verification_records')
    op.drop_index('ix_verification_records_entity', table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_production_records_verification_status'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_source_page_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_source_document_id'), table_name='production_records')
    op.drop_index('ix_production_records_project_period', table_name='production_records')
    op.drop_index('ix_production_records_mine_period', table_name='production_records')
    op.drop_table('production_records')
    op.drop_index('ix_processing_stages_job_created', table_name='processing_stages')
    op.drop_table('processing_stages')
    op.drop_index(op.f('ix_geological_measurements_verification_status'), table_name='geological_measurements')
    op.drop_index(op.f('ix_geological_measurements_source_page_id'), table_name='geological_measurements')
    op.drop_index(op.f('ix_geological_measurements_source_document_id'), table_name='geological_measurements')
    op.drop_index('ix_geological_measurements_borehole_type', table_name='geological_measurements')
    op.drop_index(op.f('ix_geological_measurements_borehole_id'), table_name='geological_measurements')
    op.drop_table('geological_measurements')
    op.drop_index('ix_extracted_tables_document_page', table_name='extracted_tables')
    op.drop_table('extracted_tables')
    op.drop_index('ix_extracted_content_page_type', table_name='extracted_content')
    op.drop_table('extracted_content')
    op.drop_index('ix_document_chunks_version_page', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_page_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_borehole_intervals_verification_status'), table_name='borehole_intervals')
    op.drop_index(op.f('ix_borehole_intervals_source_page_id'), table_name='borehole_intervals')
    op.drop_index(op.f('ix_borehole_intervals_source_document_id'), table_name='borehole_intervals')
    op.drop_index('ix_borehole_intervals_borehole_depth', table_name='borehole_intervals')
    op.drop_table('borehole_intervals')
    op.drop_index('ix_processing_jobs_version_status', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_document_pages_version_page', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_versions_sha256_checksum'), table_name='document_versions')
    op.drop_index('ix_document_versions_document_created', table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_created_by'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_boreholes_project_identifier', table_name='boreholes')
    op.drop_index(op.f('ix_boreholes_project_id'), table_name='boreholes')
    op.drop_index('ix_boreholes_location', table_name='boreholes', postgresql_using='gist')
    op.drop_index(op.f('ix_boreholes_document_id'), table_name='boreholes')
    op.drop_table('boreholes')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('ix_mining_projects_mine_name', table_name='mining_projects')
    op.drop_table('mining_projects')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256_checksum'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_validation_results_entity', table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_created_at'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_mines_name'), table_name='mines')
    op.drop_index('ix_mines_location', table_name='mines', postgresql_using='gist')
    op.drop_table('mines')
    # ### end Alembic commands ###


