"""trusted verification status fields

Revision ID: 16f153a36a30
Revises: 5ff8fa531c2a
Create Date: 2026-09-25 12:05:09.207840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '16f153a36a30'
down_revision: Union[str, None] = '5ff8fa531c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trusted_boreholes', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('trusted_geological_measurements', sa.Column('verification_status', sa.String(length=30), nullable=False))
    op.alter_column('trusted_mines', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('trusted_production_records', sa.Column('verification_status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trusted_production_records', 'verification_status')
    op.alter_column('trusted_mines', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('trusted_geological_measurements', 'verification_status')
    op.alter_column('trusted_boreholes', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
