"""semantic search indexing and audit

Revision ID: cd71ec1c4097
Revises: 16f153a36a30
Create Date: 2026-09-25 13:45:15.983353
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'cd71ec1c4097'
down_revision: Union[str, None] = '16f153a36a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('selected_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('response_status', sa.String(length=40), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_search_audits_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_audits'))
    )
    op.create_index(op.f('ix_search_audits_actor_id'), 'search_audits', ['actor_id'], unique=False)
    op.create_table('search_indexing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','COMPLETED','FAILED')", name=op.f('ck_search_indexing_jobs_status_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_search_indexing_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_search_indexing_jobs_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_search_indexing_jobs_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_indexing_jobs'))
    )
    op.create_index(op.f('ix_search_indexing_jobs_document_id'), 'search_indexing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_search_indexing_jobs_document_version_id'), 'search_indexing_jobs', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_search_indexing_jobs_status'), 'search_indexing_jobs', ['status'], unique=False)
    op.create_index('ix_search_indexing_jobs_version_created', 'search_indexing_jobs', ['document_version_id', 'created_at'], unique=False)
    op.add_column('document_chunks', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_unit_id', sa.Uuid(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_unit_type', sa.String(length=30), nullable=True))
    op.add_column('document_chunks', sa.Column('content_type', sa.String(length=80), nullable=True))
    op.add_column('document_chunks', sa.Column('evidence_type', sa.String(length=40), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_model', sa.String(length=200), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.execute("UPDATE document_chunks AS chunk SET document_id = version.document_id FROM document_versions AS version WHERE version.id = chunk.document_version_id")
    op.execute("UPDATE document_chunks SET source_unit_type = 'PAGE' WHERE source_unit_type IS NULL")
    op.execute("UPDATE document_chunks SET content_type = 'page_text' WHERE content_type IS NULL")
    op.execute("UPDATE document_chunks SET evidence_type = 'SOURCE_DOCUMENT' WHERE evidence_type IS NULL")
    op.alter_column('document_chunks', 'document_id', nullable=False)
    op.alter_column('document_chunks', 'source_unit_type', nullable=False)
    op.alter_column('document_chunks', 'content_type', nullable=False)
    op.alter_column('document_chunks', 'evidence_type', nullable=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_evidence_type', 'document_chunks', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_unit_id'), 'document_chunks', ['source_unit_id'], unique=False)
    op.create_foreign_key(op.f('fk_document_chunks_document_id_documents'), 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.execute("CREATE INDEX ix_document_chunks_embedding_cosine ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100) WHERE embedding IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_document_chunks_document_id_documents'), 'document_chunks', type_='foreignkey')
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_cosine")
    op.drop_index(op.f('ix_document_chunks_source_unit_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_evidence_type', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'embedding_dimension')
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'evidence_type')
    op.drop_column('document_chunks', 'content_type')
    op.drop_column('document_chunks', 'source_unit_type')
    op.drop_column('document_chunks', 'source_unit_id')
    op.drop_column('document_chunks', 'document_id')
    op.drop_index('ix_search_indexing_jobs_version_created', table_name='search_indexing_jobs')
    op.drop_index(op.f('ix_search_indexing_jobs_status'), table_name='search_indexing_jobs')
    op.drop_index(op.f('ix_search_indexing_jobs_document_version_id'), table_name='search_indexing_jobs')
    op.drop_index(op.f('ix_search_indexing_jobs_document_id'), table_name='search_indexing_jobs')
    op.drop_table('search_indexing_jobs')
    op.drop_index(op.f('ix_search_audits_actor_id'), table_name='search_audits')
    op.drop_table('search_audits')
    # ### end Alembic commands ###
