"""allow unpaginated source units

Revision ID: f99c9338e1e2
Revises: 15deaa701c02
Create Date: 2026-09-25 00:00:32.500778
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f99c9338e1e2'
down_revision: Union[str, None] = '15deaa701c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_document_pages_page_number_positive'), 'document_pages', type_='check')
    op.alter_column('document_pages', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_pages', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_check_constraint(op.f('ck_document_pages_page_number_positive'), 'document_pages', 'page_number > 0')
    # ### end Alembic commands ###
