import { apiRequest } from './client'
export interface SearchRequest { query: string; top_k?: number; filters?: { document_id?: string; document_version_id?: string; page_id?: string; content_type?: string; date_from?: string; date_to?: string; entity_type?: string; evidence_types?: string[] } }
export interface SearchEvidence { result_id: string; score: number; semantic_score?: number | null; lexical_score?: number | null; text: string; document_id: string; document_version_id: string; page_id?: string | null; page_number?: number | null; source_unit_id?: string | null; source_unit_type?: string | null; document_name: string; content_type?: string | null; evidence_type?: string | null; provenance?: Record<string, unknown>; context?: string; exact_source_text?: string }
export interface SemanticSearchResponse { items: SearchEvidence[]; total: number; query: string; retrieval_metadata?: { mode?: string; semantic_weight?: number; lexical_weight?: number; embedding?: Record<string, unknown> } }
export interface RagCitation { citation_id: string; document_id: string; document_name: string; document_version_id: string; page_id?: string | null; page_number?: number | null; source_unit_id?: string | null; chunk_id?: string | null; evidence_type?: string | null }
export interface RagResponse { status: string; answer: string | null; citations: RagCitation[]; evidence: SearchEvidence[]; retrieval_metadata?: Record<string, unknown>; trust_metadata?: { trusted_data_used?: boolean; source_documents_used?: boolean; trusted_data_requested?: boolean; trusted_data_available?: boolean | null; evidence_types?: string[]; authoritative_source?: string } }
export const semanticSearch = (payload: SearchRequest, signal?: AbortSignal) => apiRequest<SemanticSearchResponse>('/api/v1/search/semantic', { method: 'POST', body: JSON.stringify(payload) }, signal)
export const askWithEvidence = (payload: { question: string; top_k?: number; filters?: SearchRequest['filters'] }, signal?: AbortSignal) => apiRequest<RagResponse>('/api/v1/rag/query', { method: 'POST', body: JSON.stringify(payload) }, signal)
export const lexicalSearch = (payload: SearchRequest, signal?: AbortSignal) => apiRequest<SemanticSearchResponse>('/api/v1/search/lexical', { method: 'POST', body: JSON.stringify(payload) }, signal)
