"""canonical identity links and user role guard

Revision ID: 5ff8fa531c2a
Revises: a476290dba36
Create Date: 2026-09-25 11:58:15.336285
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5ff8fa531c2a'
down_revision: Union[str, None] = 'a476290dba36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_boreholes', sa.Column('canonical_entity_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_trusted_boreholes_canonical_entity_id'), 'trusted_boreholes', ['canonical_entity_id'])
    op.create_foreign_key(op.f('fk_trusted_boreholes_canonical_entity_id_canonical_entities'), 'trusted_boreholes', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='RESTRICT')
    op.add_column('trusted_coal_blocks', sa.Column('canonical_entity_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_trusted_coal_blocks_canonical_entity_id'), 'trusted_coal_blocks', ['canonical_entity_id'])
    op.create_foreign_key(op.f('fk_trusted_coal_blocks_canonical_entity_id_canonical_entities'), 'trusted_coal_blocks', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='RESTRICT')
    op.add_column('trusted_geological_formations', sa.Column('canonical_entity_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_trusted_geological_formations_canonical_entity_id'), 'trusted_geological_formations', ['canonical_entity_id'])
    op.create_foreign_key(op.f('fk_trusted_geological_formations_canonical_entity_id_canonical_entities'), 'trusted_geological_formations', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='RESTRICT')
    op.add_column('trusted_mines', sa.Column('canonical_entity_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_trusted_mines_canonical_entity_id'), 'trusted_mines', ['canonical_entity_id'])
    op.create_foreign_key(op.f('fk_trusted_mines_canonical_entity_id_canonical_entities'), 'trusted_mines', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='RESTRICT')
    op.add_column('trusted_projects', sa.Column('canonical_entity_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_trusted_projects_canonical_entity_id'), 'trusted_projects', ['canonical_entity_id'])
    op.create_foreign_key(op.f('fk_trusted_projects_canonical_entity_id_canonical_entities'), 'trusted_projects', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='RESTRICT')
    op.add_column('trusted_seams', sa.Column('canonical_entity_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_trusted_seams_canonical_entity_id'), 'trusted_seams', ['canonical_entity_id'])
    op.create_foreign_key(op.f('fk_trusted_seams_canonical_entity_id_canonical_entities'), 'trusted_seams', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trusted_seams_canonical_entity_id_canonical_entities'), 'trusted_seams', type_='foreignkey')
    op.drop_constraint(op.f('uq_trusted_seams_canonical_entity_id'), 'trusted_seams', type_='unique')
    op.drop_column('trusted_seams', 'canonical_entity_id')
    op.drop_constraint(op.f('fk_trusted_projects_canonical_entity_id_canonical_entities'), 'trusted_projects', type_='foreignkey')
    op.drop_constraint(op.f('uq_trusted_projects_canonical_entity_id'), 'trusted_projects', type_='unique')
    op.drop_column('trusted_projects', 'canonical_entity_id')
    op.drop_constraint(op.f('fk_trusted_mines_canonical_entity_id_canonical_entities'), 'trusted_mines', type_='foreignkey')
    op.drop_constraint(op.f('uq_trusted_mines_canonical_entity_id'), 'trusted_mines', type_='unique')
    op.drop_column('trusted_mines', 'canonical_entity_id')
    op.drop_constraint(op.f('fk_trusted_geological_formations_canonical_entity_id_canonical_entities'), 'trusted_geological_formations', type_='foreignkey')
    op.drop_constraint(op.f('uq_trusted_geological_formations_canonical_entity_id'), 'trusted_geological_formations', type_='unique')
    op.drop_column('trusted_geological_formations', 'canonical_entity_id')
    op.drop_constraint(op.f('fk_trusted_coal_blocks_canonical_entity_id_canonical_entities'), 'trusted_coal_blocks', type_='foreignkey')
    op.drop_constraint(op.f('uq_trusted_coal_blocks_canonical_entity_id'), 'trusted_coal_blocks', type_='unique')
    op.drop_column('trusted_coal_blocks', 'canonical_entity_id')
    op.drop_constraint(op.f('fk_trusted_boreholes_canonical_entity_id_canonical_entities'), 'trusted_boreholes', type_='foreignkey')
    op.drop_constraint(op.f('uq_trusted_boreholes_canonical_entity_id'), 'trusted_boreholes', type_='unique')
    op.drop_column('trusted_boreholes', 'canonical_entity_id')
    # ### end Alembic commands ###
