"""hide incomplete search vectors

Revision ID: 99633752122f
Revises: cd71ec1c4097
Create Date: 2026-09-25 14:31:20.245567
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '99633752122f'
down_revision: Union[str, None] = 'cd71ec1c4097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('is_indexed', sa.Boolean(), nullable=True))
    op.execute("UPDATE document_chunks SET is_indexed = (embedding IS NOT NULL)")
    op.alter_column('document_chunks', 'is_indexed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'is_indexed')
    # ### end Alembic commands ###
