"""trusted domain canonicalization auth

Revision ID: a476290dba36
Revises: d5f60fe4a271
Create Date: 2026-09-25 11:54:45.625649
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql


revision: str = 'a476290dba36'
down_revision: Union[str, None] = 'd5f60fe4a271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_data_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_b', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance_b', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_canonical_data_conflicts_resolved_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_data_conflicts'))
    )
    op.create_index('ix_canonical_data_conflicts_status_created', 'canonical_data_conflicts', ['status', 'created_at'], unique=False)
    op.create_table('canonical_value_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_canonical_value_history_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_canonical_value_history_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_canonical_value_history_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_value_history'))
    )
    op.create_index('ix_canonical_value_history_entity_field', 'canonical_value_history', ['entity_type', 'entity_id', 'field_name'], unique=False)
    op.create_table('trusted_coal_blocks',
    sa.Column('mineral', sa.String(length=100), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_code', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_coal_blocks_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_coal_blocks_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_coal_blocks_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_coal_blocks_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_coal_blocks_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_coal_blocks_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_coal_blocks_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_coal_blocks_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_coal_blocks_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_coal_blocks')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_coal_blocks_source_candidate_id'))
    )
    op.create_index(op.f('ix_trusted_coal_blocks_canonical_name'), 'trusted_coal_blocks', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_trusted_coal_blocks_domain_code'), 'trusted_coal_blocks', ['domain_code'], unique=False)
    op.create_index(op.f('ix_trusted_coal_blocks_normalized_name'), 'trusted_coal_blocks', ['normalized_name'], unique=False)
    op.create_table('trusted_coordinates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('coordinate_system', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_coordinates_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_coordinates_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_coordinates_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_coordinates_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_coordinates_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_coordinates_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_coordinates')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_coordinates_source_candidate_id'))
    )
    op.create_table('trusted_geological_formations',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_code', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_geological_formations_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_geological_formations_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_geological_formations_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_geological_formations_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_geological_formations_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_geological_formations_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_geological_formations_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_geological_formations_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_geological_formations_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_geological_formations')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_geological_formations_source_candidate_id'))
    )
    op.create_index(op.f('ix_trusted_geological_formations_canonical_name'), 'trusted_geological_formations', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_trusted_geological_formations_domain_code'), 'trusted_geological_formations', ['domain_code'], unique=False)
    op.create_index(op.f('ix_trusted_geological_formations_normalized_name'), 'trusted_geological_formations', ['normalized_name'], unique=False)
    op.create_table('trusted_mines',
    sa.Column('operator', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_code', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_mines_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_mines_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_mines_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_mines_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_mines_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_mines_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_mines_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_mines_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_mines_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_mines')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_mines_source_candidate_id'))
    )
    op.create_index(op.f('ix_trusted_mines_canonical_name'), 'trusted_mines', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_trusted_mines_domain_code'), 'trusted_mines', ['domain_code'], unique=False)
    op.create_index(op.f('ix_trusted_mines_normalized_name'), 'trusted_mines', ['normalized_name'], unique=False)
    op.create_table('trusted_projects',
    sa.Column('mine_id', sa.Uuid(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_code', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['trusted_mines.id'], name=op.f('fk_trusted_projects_mine_id_trusted_mines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_projects_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_projects_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_projects_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_projects_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_projects_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_projects_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_projects_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_projects_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_projects_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_projects')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_projects_source_candidate_id'))
    )
    op.create_index(op.f('ix_trusted_projects_canonical_name'), 'trusted_projects', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_trusted_projects_domain_code'), 'trusted_projects', ['domain_code'], unique=False)
    op.create_index(op.f('ix_trusted_projects_normalized_name'), 'trusted_projects', ['normalized_name'], unique=False)
    op.create_table('trusted_seams',
    sa.Column('formation_id', sa.Uuid(), nullable=True),
    sa.Column('commodity', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_code', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['trusted_geological_formations.id'], name=op.f('fk_trusted_seams_formation_id_trusted_geological_formations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_seams_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_seams_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_seams_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_seams_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_seams_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_seams_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_seams_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_seams_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_seams_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_seams')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_seams_source_candidate_id'))
    )
    op.create_index(op.f('ix_trusted_seams_canonical_name'), 'trusted_seams', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_trusted_seams_domain_code'), 'trusted_seams', ['domain_code'], unique=False)
    op.create_index(op.f('ix_trusted_seams_normalized_name'), 'trusted_seams', ['normalized_name'], unique=False)
    op.create_table('trusted_boreholes',
    sa.Column('mine_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('elevation', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('depth', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain_code', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['trusted_mines.id'], name=op.f('fk_trusted_boreholes_mine_id_trusted_mines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['trusted_projects.id'], name=op.f('fk_trusted_boreholes_project_id_trusted_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_boreholes_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_boreholes_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_boreholes_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_boreholes_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_boreholes_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_boreholes_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_boreholes_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_boreholes_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_boreholes_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_boreholes')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_boreholes_source_candidate_id'))
    )
    op.create_index(op.f('ix_trusted_boreholes_canonical_name'), 'trusted_boreholes', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_trusted_boreholes_domain_code'), 'trusted_boreholes', ['domain_code'], unique=False)
    op.create_index(op.f('ix_trusted_boreholes_normalized_name'), 'trusted_boreholes', ['normalized_name'], unique=False)
    op.create_table('trusted_production_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mine_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('reporting_period', sa.String(length=40), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=True),
    sa.Column('production_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('production_unit', sa.String(length=50), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['trusted_mines.id'], name=op.f('fk_trusted_production_records_mine_id_trusted_mines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['trusted_projects.id'], name=op.f('fk_trusted_production_records_project_id_trusted_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_production_records_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_production_records_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_production_records_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_production_records_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_production_records_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_production_records_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_production_records_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_production_records_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_production_records_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_production_records')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_production_records_source_candidate_id'))
    )
    op.create_table('trusted_geological_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('measurement_type', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('depth_from', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('depth_to', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('source_table_id', sa.Uuid(), nullable=True),
    sa.Column('source_cell_id', sa.Uuid(), nullable=True),
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('borehole_id', sa.Uuid(), nullable=True),
    sa.Column('seam_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['trusted_boreholes.id'], name=op.f('fk_trusted_geological_measurements_borehole_id_trusted_boreholes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seam_id'], ['trusted_seams.id'], name=op.f('fk_trusted_geological_measurements_seam_id_trusted_seams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['extraction_candidates.id'], name=op.f('fk_trusted_geological_measurements_source_candidate_id_extraction_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_cell_id'], ['extracted_table_cells.id'], name=op.f('fk_trusted_geological_measurements_source_cell_id_extracted_table_cells'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_content_id'], ['extracted_content.id'], name=op.f('fk_trusted_geological_measurements_source_content_id_extracted_content'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_trusted_geological_measurements_source_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_page_id'], ['document_pages.id'], name=op.f('fk_trusted_geological_measurements_source_page_id_document_pages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_table_id'], ['extracted_tables.id'], name=op.f('fk_trusted_geological_measurements_source_table_id_extracted_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_trusted_geological_measurements_source_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_id'], ['canonical_records.id'], name=op.f('fk_trusted_geological_measurements_verification_id_canonical_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], name=op.f('fk_trusted_geological_measurements_verifier_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_geological_measurements')),
    sa.UniqueConstraint('source_candidate_id', name=op.f('uq_trusted_geological_measurements_source_candidate_id'))
    )
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default=sa.text("'VIEWER'"), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_check_constraint(op.f('ck_users_role_valid'), 'users', "role IN ('ADMIN','VERIFIER','ANALYST','VIEWER')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(op.f('ck_users_role_valid'), 'users', type_='check')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'role')
    op.drop_table('trusted_geological_measurements')
    op.drop_table('trusted_production_records')
    op.drop_index(op.f('ix_trusted_boreholes_normalized_name'), table_name='trusted_boreholes')
    op.drop_index(op.f('ix_trusted_boreholes_domain_code'), table_name='trusted_boreholes')
    op.drop_index(op.f('ix_trusted_boreholes_canonical_name'), table_name='trusted_boreholes')
    op.drop_table('trusted_boreholes')
    op.drop_index(op.f('ix_trusted_seams_normalized_name'), table_name='trusted_seams')
    op.drop_index(op.f('ix_trusted_seams_domain_code'), table_name='trusted_seams')
    op.drop_index(op.f('ix_trusted_seams_canonical_name'), table_name='trusted_seams')
    op.drop_table('trusted_seams')
    op.drop_index(op.f('ix_trusted_projects_normalized_name'), table_name='trusted_projects')
    op.drop_index(op.f('ix_trusted_projects_domain_code'), table_name='trusted_projects')
    op.drop_index(op.f('ix_trusted_projects_canonical_name'), table_name='trusted_projects')
    op.drop_table('trusted_projects')
    op.drop_index(op.f('ix_trusted_mines_normalized_name'), table_name='trusted_mines')
    op.drop_index(op.f('ix_trusted_mines_domain_code'), table_name='trusted_mines')
    op.drop_index(op.f('ix_trusted_mines_canonical_name'), table_name='trusted_mines')
    op.drop_table('trusted_mines')
    op.drop_index(op.f('ix_trusted_geological_formations_normalized_name'), table_name='trusted_geological_formations')
    op.drop_index(op.f('ix_trusted_geological_formations_domain_code'), table_name='trusted_geological_formations')
    op.drop_index(op.f('ix_trusted_geological_formations_canonical_name'), table_name='trusted_geological_formations')
    op.drop_table('trusted_geological_formations')
    op.drop_table('trusted_coordinates')
    op.drop_index(op.f('ix_trusted_coal_blocks_normalized_name'), table_name='trusted_coal_blocks')
    op.drop_index(op.f('ix_trusted_coal_blocks_domain_code'), table_name='trusted_coal_blocks')
    op.drop_index(op.f('ix_trusted_coal_blocks_canonical_name'), table_name='trusted_coal_blocks')
    op.drop_table('trusted_coal_blocks')
    op.drop_index('ix_canonical_value_history_entity_field', table_name='canonical_value_history')
    op.drop_table('canonical_value_history')
    op.drop_index('ix_canonical_data_conflicts_status_created', table_name='canonical_data_conflicts')
    op.drop_table('canonical_data_conflicts')
    # ### end Alembic commands ###
